language: java
sudo: false # faster builds

jdk:
  - openjdk8

branches: # build only on these branches
  only:
    - master
    - dev

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true